### ISSUE TITLE
HPC Carpentry @ CarpentryCon@HOME

### ISSUE THREAD

**Issue by ocaisa** [carpentries-incubator/hpc-intro#123]
Hi all, @psteinb and I just opened a breakout session request at https://github.com/carpentrycon/carpentryconhome-proposals/issues/33 in case people want to comment or volunteer to contribute there.

Is anyone else considering a session?

**Comment by psteinb** [comment]
Our proposal was accepted.

**Comment by tkphd** [comment]
:tada:

**Comment by ocaisa** [comment]
@tkphd Now that we have 2 sessions for the different timezones, we need a couple more lightning talks.

You've been really active the last couple of weeks and it might be nice to have a lightning talk on what you consider the status of this lesson to be. Are you up for it? If so, can you come up with a title and add it to the Agenda at https://pad.carpentries.org/cchome-hpc-carpentry

Would be much appreciated...

**Comment by tkphd** [comment]
Of course, @ocaisa, I'd be happy to. Etherpad is updated, I plan to talk about the status of portability (templating & streamlining efforts): more on the back-end than curriculum development. @reid-a & I have been working through customization for our cluster, which is producing to-do lists on both sides.

**Comment by annajiat** [comment]
I was looking forward to attend the 2nd session but it got postponed. Signed up to be notified of a potential re-scheduled session at https://pad.carpentries.org/cchome-maintainer-git-skills

**Comment by tkphd** [comment]
While we wait, the first session was recorded, and has been [posted on YouTube!](https://www.youtube.com/watch?v=uvWhSYBkZJ0&list=PLXLapl_LKb4fx-t_4MBSPiefTraj5KdJ8&index=3)

**Comment by bkmgit** [comment]
@ocaisa Can this be closed?

**Comment by ocaisa** [comment]
For sure
