### ISSUE TITLE
The why of cluster is missing 

### ISSUE THREAD

**Issue by kamil963** [carpentries-incubator/hpc-intro#15]
The why of cluster is missing 
Cloud and cluster are defined as terms.  But why should a researcher care?

Anwser:
   Cloud typically runs services.
   Cluster runs batch jobs.

Cloud is better when you need to run a service such as a website, or database.

Cluster is better when a researcher needs to run one or more computations (ex simulation or data processing) where it is not really important exactly when the computation runs and where it may take a while for enough resources to become available to run the computation.   

Would it not be great if there was something that orchestrated  the resources, started your computation when enough resources were available to run even if its 4 am, and emailed you when your computation was done. This is what a HPC cluster does, and why you would use one.

The exact nomenclature computation/simulation/job of this discussion will be difficult to have without invoking other not defined words.

**Comment by ChristinaLK** [comment]
See also #7

**Comment by psteinb** [comment]
related to this, a lengthy on __what HPC is__:
https://www.hpcnotes.com/2015/10/essential-analogies-for-hpc-advocate.html

**Comment by tkphd** [comment]
Nice article! Thanks for linking, @psteinb.

**Comment by bkmgit** [comment]
Related issue is #235 and #117. It is partially addressed in https://carpentries-incubator.github.io/hpc-intro/11-hpc-intro/index.html so can probably be closed.

**Comment by tkphd** [comment]
"Can probably be closed" is music to my ears.
