### ISSUE TITLE
fastq files do not exist

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#154]
In ep. 15, we discuss ways to transfer files, but *never actually do it.*
This leads to significant confusion in ep. 17, when learners are expected to run `fastqc` on a set of `fastq` files that are nowhere to be found on the cluster.

This requires crafting a new challenge, with complete solution, to download, unpack, and transfer the contents of `bash-lesson.tar.gz`.

**Comment by psteinb** [comment]
and one wonders if that would overlaps with [`hpc-shell`](https://github.com/hpc-carpentry/hpc-shell) as there is a `ssh` lesson inplace already?

For possible contributors, feel free to adapt https://psteinb.github.io/hpc-in-a-day/01-01-logging-in/ if deemed appropriate with proper attribution. I'll do it myself if time permits.

**Comment by tkphd** [comment]
Deprecated by #255, which would purge `fastqc`.
