### ISSUE TITLE
using 2 cpus

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#158]
The default interactive example, `ComputeCanada_Graham_slurm/13/interactive_example.snip`, states that the job will use 2 CPUs, and asserts success on receiving `This job will use 2 CPUs.` as output.

If the job had actually used 2 CPUs, the output would read
```bash
This job will use 2 CPUs.
This job will use 2 CPUs.
```

With the Slurm flag `-c 2`, the job spins up one CPU and is *given permission* to use two *threads*. Since `echo` is not thread-aware, this results in only one line of output from the one CPU and one thread that actually launched. Slurm does not handle threads, only MPI ranks; using threads is left to the user, typically via OpenMP.

If we really want to launch on 2 CPUs, the job needs `-n 2`, and the output needs to be corrected.

**Comment by psteinb** [comment]
in slurm speak, `-n 2` however can make the job run on 2 different nodes. Is that OK with this snippet?

**Comment by tkphd** [comment]
If you have a truly single-core processor, yes, Slurm can get confused in this way. Given the widely SMP nature of modern CPUs, you would have to build a niche cluster to encounter this error.

If we really want to make sure, we can specify `-N 1 -n 2`, but I believe that is overkill.

**Comment by tkphd** [comment]
This was addressed somewhere along the line, but the issue was not closed.
