### ISSUE TITLE
using one full node

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#159]
In Ep. 13 "Submitting resource requests," poses this challenge: "Submit a job that will use 1 full node and 1 minute of walltime."

To "use 1 full node" would require the `--exclusive` flag in Slurm, or its equivalent. However, I suspect this is not what is meant. Rather, we want to use *no more than 1 node*, and 1 minute of walltime. This would be consistent with the rest of the text, which leaves the defaults (one node, one CPU, or `-N1 -n1`) alone. 

Revision for better clarity (and accuracy in the challenge) would be welcome.

**Comment by psteinb** [comment]
Question to me: is enforced exclusive use of a node even possible with any other scheduler than slurm? IIRC my days on the use of LSF, I do think we made this explicit by requiring a job to use as many cores as we knew the nodes expose. This would then mean that this snippet will expose a great dependency on the local setup of a cluster.
This to be taken into account.

**Comment by tkphd** [comment]
Yeah, I think the issue is *clumsy phrasing*, no that we would actually want to take exclusive control of a node.

**Comment by reid-a** [comment]
Yes, Torque/Maui can do this, with an argument:

> -W x=NACCESSPOLICY:SINGLEJOB 

   ... to the "qsub" command.  This permits you to "undersubscribe"
a node on CPU/core counts -- you typically do this because you want
all the RAM, or have some other requirement that's not well-managed
by the queuing system.

  My GridEngine skills are a bit rusty, but it looks like there's
a "-l exclusive=1" option for SGE's qsub command.  I found it here:

> https://docs.hpc.udel.edu/technical/gridengine/exclusive-alloc#configuring-exclusive-access

  It looks like it's new as of version 6u2 -- not sure how new
that is, really.

					-- A.


On Mon, Jul 20, 2020 at 02:42:35AM -0700, Peter Steinbach wrote:
> Question to me: is enforced exclusive use of a node even possible with any
> other scheduler than slurm? IIRC my days on the use of LSF, I do think we made
> this explicit by requiring a job to use as many cores as we knew the nodes
> expose. This would then mean that this snippet will expose a great dependency
> on the local setup of a cluster.
> This to be taken into account.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 
Dr. Andrew C. E. Reid
Physical Scientist, Computer Operations Administrator
Center for Theoretical and Computational Materials Science
National Institute of Standards and Technology, Mail Stop 8555
Gaithersburg MD 20899 USA
andrew.reid@nist.gov

**Comment by psteinb** [comment]
Thanks for these pointers, so it might be doable after all.

**Comment by tkphd** [comment]
Undersubscribing a node is definitely not an introductory topic.

**Comment by psteinb** [comment]
So, I sense that we agree that the text needs to be revised to gear the learners towards requesting one full node only - not more, not less.

**Comment by tkphd** [comment]
I think we've gotten lost in the details here. Perhaps recasting this in terms of what [this challenge](https://github.com/hpc-carpentry/hpc-intro/blob/gh-pages/_episodes/13-scheduler.md#submitting-resource-requests) is about will help us move forward. 

Learners have only just seen how to add the job name to their script (in "Customising a Job"), with a challenge problem for adding email notifications. Then comes a section on Resource Requests, and a short list of options you will regularly see in batch scripts. At present, this list includes `-n <ntasks>`, `-c <ncpus>`, `--mem=<megabytes>`, and `--time <days-hours:minutes:seconds>`. It does not include `-N <nnodes>` or `--exclusive`.

From a pedagogical standpoint, we've exercised the use of batch job flags, with some easy-to-grasp options: pick a name, insert your email. This is a good, gentle, reinforcing approach. Then we come to more gritty details, for which you ought to know something about the job to be run. Setting a time limit seems like a logical next step, since we can guess -- and, even better, run and see -- how long it ought to take for `hostname` to complete. 

What else do we want to teach at this point? I think adding one more thing makes sense, at least, and it should be something commonly used. To my mind, the number of MPI tasks (`-n`) makes sense: setting `-n 1` makes sense (`hostname` runs serially on the localhost), and we could craft a challenge problem to run with increasing numbers, until we see two different hostnames in the output. Once we find that output, of course, which is another exercise.

We could teach `--exclusive` here. I'm not convinced that's a responsible thing to do, since it's an option I have never used, and pushing "real" jobs out of the way so that we can run "hostname" on a full node seems wrong, and would tend to bog down the queue. What is our intent, in terms of teaching both concepts and good behavior?
