### ISSUE TITLE
Add distinction between multiple tasks and multiple nodes

### ISSUE THREAD

**Issue by jstaf** [carpentries-incubator/hpc-intro#18]
This was holding up the merge of https://github.com/hpc-carpentry/hpc-intro/pull/4, but a distinction should be added between multiple tasks (`-n`) and multiple nodes (`-N`). Maybe add this as a callout box?

**Comment by psteinb** [comment]
this is a slurm specific thing. Other schedulers don't honor this difference so strong as slurm does.

I'd personally suggest to avoid this discussion at all costs as it might confuse people more than it helps. From my perspective, the distinction comes from the difference of a resource (node, `-N`) and a portion of work (task, `-n`).

**Comment by reid-a** [comment]
We now (Jan. 2021) have a snippets library for the arguments for specific resource managers.
The "Running a Paralell Job" example has -N 1 and -n 4 in the slurm configuration. Verify that other queuing systems are correctly represented, and close this.

**Comment by tkphd** [comment]
As @psteinb noted, this is a Slurm specific thing, so other queuing systems are out of scope. This issue is Resolved.
