### ISSUE TITLE
Opting in for beling enlisted as "help wanted" on carpentries site 

### ISSUE THREAD

**Issue by annajiat** [carpentries-incubator/hpc-intro#228]
Hi,
Should we fill up 
    "Help Wanted" page opt-in: https://forms.gle/Gdizcu633U3LNR5r6

**Comment by reid-a** [comment]
The linked form includes a blank for the repo URL. One of the things we learned from the Sept. 16 [task force meeting](https://codimd.carpentries.org/ct7yfc_LSseoC8mEmbVEiQ?both) is that, if we join the Carpentries Incubator, our URL will change.

Joining the incubator also makes us more visible to the wider Carpentries community.

I suggest we hold off on this until we have a clearer idea of the incubator time-line.

**Comment by reid-a** [comment]
By way of follow-up, apparently that form is intended for Carpentries-hosted projects, so we would not actually be considered for inclusion in the help-wanted family until we were in the incubator in any case. This creates a dependency for this item, but IMO it's still a good idea!

**Comment by reid-a** [comment]
Updatge Januarly 2021, we are now in the Carpentries incubator, so I think there is no barrier to doing this?
To reduce confusion among newcomers to the repo, maybe hold off until the Jan. 2021 issue-cleanup is farther along?

**Comment by tobyhodges** [comment]
Indeed, now this repo is in the Incubator, you could list issues on the page as soon as you are ready.

**Comment by tkphd** [comment]
"The form "Help Wanted" Page - Lesson Opt-In is no longer accepting responses.
Try contacting the owner of the form if you think this is a mistake."

**Comment by tobyhodges** [comment]
> "The form "Help Wanted" Page - Lesson Opt-In is no longer accepting responses.

We used the form to collect opt-ins initially, but now we ask maintainers to send a request to be listed on the page to team@carpentries.org. It might have been simpler to keep the form open... Regardless, I will consider this a request for this repository to be added and will take care of it from here.

**Comment by tkphd** [comment]
Thank you!

**Comment by tobyhodges** [comment]
Update: issues labelled `help-wanted` are now being listed on https://carpentries.org/help-wanted-issues/#repo-name-carpentries-incubator-hpc-intro
