### ISSUE TITLE
Introduce non-sequential lesson numbering

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#230]
This issue is the successor of #226, which was partially addressed by renaming the snippet directories.

The remaining issue is that the lesson files under `_episodes` have sequential numeric prefixes, which controls the order in which they appear in the built website. Getting this order right is important, but the sequential numeric prefixes hinder flexibility.

However, moving away from this is not entirely trivial, because the build-test scripts assume the existence and sequential character of these prefixes. Any change to this involves a change to the build-tests, which came from the upstream Carpentries style, and so should be coordinated with them.

There is an [upstream issue](https://github.com/carpentries/styles/issues/502) on this.

Obvious options are to have gaps in the numeric ordering, or to just use descriptive names, and control the ordering [manually](https://github.com/carpentries/styles/blob/gh-pages/_includes/manual_episode_order.html).

**Comment by tkphd** [comment]
See also #9 .

**Comment by psteinb** [comment]
We've been informed by @tobyhodges that the lesson template now offers mechanisms to ditch the numerical ordering by means of a dedicated slug in `_config.yml`. I can't find the issue/PR at this moment or any hints to the documentation of `episode_order`. In any case, this is how to use it:

```yaml
episode_order:
  - 10-hpc-intro.md
  - 15-cluster.md
  - 45-responsibility.md
  - 20-scheduler.md
  - 25-modules.md
  - 30-transferring-files.md
  - 35-parallel.md
  - 40-resources.md
```

@tobyhodges can you provide more details?

**Comment by reid-a** [comment]
Testing reveals that if you just add the block above to your site-specific _config.yml, except without the ".md" extensions, it works. You can re-order or omit lessons, and it builds correctly.

A commit will likely be forthcoming that modifies the NIST_CTCMS config to omit modules, which we do not use.

**Comment by tobyhodges** [comment]
Looks good. I've made a note to add at least some mention of this feature in our documentation.

**Comment by tobyhodges** [comment]
This ordering of episodes and extras is now documented in [the Lesson Example](https://carpentries.github.io/lesson-example/03-organization/index.html#episode_order).
