### ISSUE TITLE
"make serve" forces global config change to bundle

### ISSUE THREAD

**Issue by wirawan0** [carpentries-incubator/hpc-intro#239]
Hi, I noticed the recent change in `JEKYLL` var in lesson's `Makefile` leads to a global change in my `~/.bundle/config` that is undesirable. I have MacOS with ruby fed from Homebrew. I have been installing all the Jekyll gem dependencies to build Carpentry-style webpages with "bundle install" once, and for all lessons I was able to simply run "bundle exec make serve". But the recent change to hpc-intro in commit 4b880e32b9304dc964ec557342cea8d9c0c0211f causes `.vendor/bundle` to be set for *every* lesson repo I have--causing fatal error every time I wanted to compile lessons other than hpc-intro. Turned out that this config would force me to do "bundle install" for every lesson repo I have (and I have many of them--over 10). @ocaisa , may you please explain why the change in the JEKYLL definition in the first place? I am trying to avoid installing lesson-specific gems for every lesson if at all possible.

**Comment by ocaisa** [comment]
Hi @wirawan0 , when I made this change upstream in https://github.com/carpentries/styles/pull/473 they caught that I was making a global config change but I forgot to merge the updates there back to this repo. That is now done in #240.
