### ISSUE TITLE
revise URLs

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#243]
`index.md` and `README.md` point to <https://hpc-carpentry.github.io/hpc-intro>. These links should be updated to <https://carpentries-incubator.github.io/hpc-intro/>

**Comment by tkphd** [comment]
The links should definitely be updated, but you can configure GitHub to serve the content at different addresses. We should try configuring it for hpc-carpentry.org/hpc-intro.

**Comment by reid-a** [comment]
More detailed instructions on the custom domain are [here](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site).

To have the site render at "hpc-carpentry.org/hpc-intro", the appropriate procedure is the "apex domain" one, which is the second part of the instructions. It is not clear to me on initial reading if this will break the existing hpc-carpentry.org functionality.

What *is* clear is that the appropriate action has to be taken by the owner of the hpc-carpentry.org domain, which is @ocaisa.

**Comment by ocaisa** [comment]
Placing it in `hpc-carpentry.org/hpc-intro` is not possible (AFAIK) since the repository is no longer part of the `hpc-carpentry` organisation, it needed to placed in a separate subdomain. http://hpc-intro.hpc-carpentry.org/ is now live!

**Comment by reid-a** [comment]
Thank you @ocaisa !
Closing this issue.

**Comment by tkphd** [comment]
Warnings being thrown on forks described in #284.
