### ISSUE TITLE
Document maintenance practices of the repo in MAINTAINING.md or similar

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#265]
The repo and the community seem to be accreting some conventional practices, e.g. the Zenodo webhook that generates a DOI for releases (from issue #136), and possibly others. We should collect this info into a single file which describes our solutions to various logistical issues that have arisen.

**Comment by tkphd** [comment]
- [ ] Zenodo webhook (created by @psteinb at my prompting)
- [ ] GitHub teams with permissions, and how to join
- [ ] The various comms channels (TopicBox, GitHub, and Slack)

**Comment by reid-a** [comment]
Draft description of the various web-based resources.  These are deliberately not links, just addresses.

### E-mail:

The top-level site is carpentries.topicbox.com. There are two HPC-specific lists, "discuss-hpc" and "maintainers-hpc". The system does not use passwords, log-ins are via a verification code sent to your e-mail. I don't recall how to join the lists, my recollection is that anyone can participate in "discuss-hpc", but "maintainers-hpc" is by invitation?

### Slack:

 The main Carpentries slack channel is reachable at swcarpentry.slack.com. You can go directly to the HPC Carpentry sub-channel at swcarpentry.slack.com/#hpc-carpentry. These are the things to bookmark -- once you go there, the Slack engine redirects you to particular views, so cutting/pasting URLs out of the browser's location bar is likely to be disappointing. Anyone can join(?), default authentication is via a password that's common across many slack channels.

### Github: 

#### Carpentries-Incubator

HPC-Intro is currently on Github at github.com/carpentries-incubator/hpc-intro. Your account is in the scope of github as a whole, but in order to get write access to the repo, you will need to become a member of the HPC Intro Maintainers team, which lives inside the "carpentries-incubator" project (whose base URL is github.com/carpentries-incubator.

#### HPC-Carpentry

There is also an HPC Carpentry Github project github.com/hpc-carpentry, which has other HPC-related lessons repos in its scope, and separate teams of maintainers and administrators. 

In particular, there is a "coordination" repo, github.com/hpc-carpentry/coordination, which is a good scope for issues and concerns for the HPC carpentry community at large, rather than any particular lesson. 

There is also a repo for the main website covering all HPC-Carpentry activities, /github.com/hpc-carpentry/hpc-carpentry.org. This is intended to be the "front door" of the HPC Carpentry community.

**Comment by tkphd** [comment]
Looks good in general. I think we should rank-order by traffic, so, GitHub, then Slack, then TopicBox. Perhaps call out the coordination/minutes folder, and outline the use of The Carpentries' live meeting notes platform -- Etherpad previously, currently CodiMD.

For Slack, anyone who is already a member of any channel on /swcarpentry.slack.com, they can type "hpc-carpentry" in the "Search the Carpentries" box up top to join us. For those who have not yet joined the hivemind, they need an invitation to join. Fortunately, The Carpentries provides an auto-granting app for this: they need only click on the link, /swc-slack-invite.herokuapp.com/

*Links have been deliberately broken for consistency, though I do not understand the reasoning.*

**Comment by reid-a** [comment]
The closure of issue #243 means that the site renders on a different domain than the github default -- the maintenance document should also describe how that works.
