### ISSUE TITLE
Simplify file transfer section

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/hpc-intro#27]
Somewhat related to #20, I think we should present *one* clear option in the file transfer section (https://hpc-carpentry.github.io/hpc-intro/14-transferring-files/) and then refer people to other tools in the "extras" section.

**Comment by pdoehle** [comment]
+1

**Comment by psteinb** [comment]
I personally would go with `scp` for now as it is very close to `ssh` ;)

**Comment by CarrieBrown** [comment]
Agree with SCP as the one option offered.

Include a "generic" command format example in the section, such as:
`scp <source_host>:<source_file> <target_host>:<target_file>`

**Comment by CarrieBrown** [comment]
Removed sftp in PR #96 

Was unsure about the filezilla section, so I left it in for now.

**Comment by bkmgit** [comment]
Current version of hpc-intro seems clear on this. This issue can be closed.

**Comment by tkphd** [comment]
@bkmgit please feel free to hit that "Close with comment" button!
