### ISSUE TITLE
Consider using Anaconda for module example instead of regular Python 3

### ISSUE THREAD

**Issue by mikerenfro** [carpentries-incubator/hpc-intro#273]
Since stock Python 3 will be increasingly common from OS vendors, and since the Pi example requires numpy, it may make sense to adjust the module and Pi episodes to:

- load an Anaconda module instead of a Python 3 module, since Anaconda would include numpy by default, and the OS-provided Python 3 won't
- adjust Pi job script to use new module

**Comment by tkphd** [comment]
Pedagogically, it's better to load the Python module. For HPC, this module should have numpy already as well.

Developing an interchangeable Anaconda lesson, for clusters where modules are unavailable, would be valuable.

**Comment by mikerenfro** [comment]
Suits me. I can adjust instruction to match our local setup when needed.
