### ISSUE TITLE
More precise wording on scatter/gather

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#279]
The recently-updated parallel lesson has descriptive text which is possibly misleading, it defines:

 * Scatter: an MPI operation wherein the process running on one rank sends a piece of 
     information (value, array, or object) to all others on the given comm.
 * Gather: the inverse of Scatter, one rank receives a piece of information from all

This is imprecise.

What scatter does more precisely is partition an array and send different array fragments to the partner ranks, with each rank getting a different portion of the array. The current text is a description of a broadcast operation, where all of the partner ranks get the same data from the sending rank.

What gather does more precisely is populate different portions of a local array with data from the various partner ranks. There maybe many "pieces of information".

Having gone through the MPI documentation, i can find no indication that scatter and gather can work on non-array objects, but I am not an MPI expert.

A description of "scatter" that overlaps with what "broadcast" actually does is potentially confusing for newcomers to the concept of parallelism and data heterogeneity.

Proposed revision:
* Scatter: An MPI operation in which an array of data is divided up, with separate portions being sent out
    to the partner ranks. Each partner rank receives data from a different part of the array.
* Gather: The inverse of scatter. One rank populates a local array, with different portions of the array populated
    by data from different partner ranks.

**Comment by tkphd** [comment]
You are correct, MPI Scatter cannot distribute a scalar value. It must be an array of *N* items, one per rank in the communicator.

```python
#!/usr/bin/env python3

from mpi4py import MPI

comm = MPI.COMM_WORLD
cpus = comm.Get_size()
rank = comm.Get_rank()

if __name__ == '__main__':
    indiana_pi = comm.scatter([3.2], root=0)
    print("Rank {}: π is {:n}.".format(rank, indiana_pi))
```

```bash
$ mpirun -np 1 scatter.py 
Rank 0: π is 3.2.
```
```bash
$ mpirun -np 2 scatter.py 
Traceback (most recent call last):
  File "/home/thor/repositories/carpentries/hpc-intro/files/scatter.py", line 10, in <module>
    indiana_pi = comm.scatter([3.2], root=0)
  File "mpi4py/MPI/Comm.pyx", line 1267, in mpi4py.MPI.Comm.scatter
  File "mpi4py/MPI/msgpickle.pxi", line 730, in mpi4py.MPI.PyMPI_scatter
  File "mpi4py/MPI/msgpickle.pxi", line 119, in mpi4py.MPI.Pickle.dumpv
ValueError: expecting 2 items, got 1
```
