### ISSUE TITLE
wrap markdown at 79 columns

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#282]
The GitHub `diff` interface wraps lines at 80 characters. Since we use 100 characters as the max width, this makes for ugly `diff`s with lots of continued lines. To improve the clarity of these diffs, as well as readability in terminal text editors, we should back away from this edge, and wrap our content at 79 characters.

This is easily done with emacs, but the change would touch almost every file in the repository, so this should be coordinated with other efforts to minimize merge conflicts and the number of branch rebases to be done.

**Comment by mikerenfro** [comment]
Re: readability of diffs, could we consider adding [semantic linebreaks](https://rhodesmill.org/brandon/2012/one-sentence-per-line/) as well? So <=79 characters per line, plus breaks at ends of sentences, major clauses, etc.?

**Comment by tkphd** [comment]
We could, and for code & LaTeX, I am definitely in favor.
To my eye, the semantic linebreaks interrupt readability of the text, and Markdown is meant to be human-readable first. It's also a touch more difficult to configure a text editor to automate this wrapping, but that's a minor technical thing, not a reason either way.

Curious what other folks think. Please weigh in!

**Comment by mikerenfro** [comment]
One comparison for later reference: the Email section of [d1792148](https://github.com/carpentries-incubator/hpc-intro/commit/d1792148104dd269ac8f5ca60dde5ce31a56143a#) versus [equivalent changes with semantic line breaks already present](https://github.com/mikerenfro/topicbox/commit/e1166c49715fd39c1dfd76cd5336d31ba7396682)

**Comment by tkphd** [comment]
That's a helpful direct comparison, thanks Mike. My inner voice *stops* at the end of those semantically-broken lines, which I find uncomfortable, but am happy to be overruled.
