### ISSUE TITLE
Ensure snippets are valid Markdown

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#320]
Superficially, this issue regards Ep. 16, in which [we have](https://github.com/carpentries-incubator/hpc-intro/blame/gh-pages/_episodes/16-parallel.md#L320)

```markdown
    ```
    {% include {{ site.snippets }}/parallel/one-task-with-memory-jobscript.snip %}
    ```
    {: .output}
```

The code block and syntax hinting should be inside the included file, not in the lesson.

This should be checked across all the snippet files, and we should consider renaming the snippets from `.snip` to `.md` to make this clear. A challenge is that Jekyll would probably try to build these files, in addition to including them, which we do not want.

**Comment by ocaisa** [comment]
I struggled with this a bit because the syntax hinting is `{: .output}` due to the fact the previous command used was `cat`. That context is not available in the snippet where the obvious choice would be `{: .source}` , it's a detail but it was enough to push me to in the direction that exists now.

**Comment by tkphd** [comment]
The included file contains a shell script, not terminal output. `language-bash` is the appropriate hinting.
This issue is more about where that hinting belongs (inside the snippet) than what hint is specified, but we should address both.

**Comment by ocaisa** [comment]
Maybe we can just add `.snip` as a valid markdown extension in the `lesson_check.py` and add `_includes/snippets/*/*` as valid places to look for markdown files

**Comment by ocaisa** [comment]
I tried to do this and t is mostly but for no good reason `lesson_check.py` complains about `_includes/snippets_library/UCL_Myriad_sge/modules/wrong-gcc-version.snip`

I'll make a PR, but I don't know how to get the CI to pass for that, I've spent an hour trying to figure out what is wrong. It also doesn't pick up that that the two files that triggered this issue are not markdown.

**Comment by tkphd** [comment]
Addressed by #322. The motivating issue, which is that snippets like [four-tasks-jobscript.snip](https://github.com/carpentries-incubator/hpc-intro/blob/gh-pages/_includes/snippets_library/Magic_Castle_EESSI_slurm/parallel/four-tasks-jobscript.snip) contain code *without* placing it in a codeblock, persists. 

Consider adding `mdl` ([markdownlint](https://github.com/markdownlint/markdownlint)) to the Gemfile and running it on all `.md` and `.snip` files. This will throw a *lot* of errors.

**Comment by tkphd** [comment]
Closed by 0029f46.
