### ISSUE TITLE
explore a node is fully templated

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#328]
The Explore a Worker Node challenge text in `cluster/specific-node-info.snip` contains nothing site- or scheduler-specific, and is identical across all libraries. Merge its contents back into `12-cluster.md` and reduce the snippets to just the job-launching shell command.

**Comment by reid-a** [comment]
The `specific-node-info.snp` file includes the local site prompt, which is site-specific, so I think this actually can't be eliminated.

**Comment by tkphd** [comment]
That file is entirely templated: the local prompt is not hard-coded, its value comes from the specified `_config.yml`. The entire text of the snippet should be restored to `12-cluster.md`, with no loss of content or intent.

**Comment by tkphd** [comment]
Ah, but the snippet command is scheduler-specific. Rats!
