### ISSUE TITLE
Invitation to present HPC carpentries to Norwegian training partners 

### ISSUE THREAD

**Issue by Sabryr** [carpentries-incubator/hpc-intro#361]
I am opening an issue instead of contacting individuals, to make a short (15) min presentation on 
1. How you adopted HPC carpentry material for your own institute. For example snippets and config options to custoimize.
2. How could contributing to a community effort is a win-win (or not)
 
Date : 21-June-2020
Time :11:00 CET

Please show your interest as reply here and I will send the calendar invite.

**Comment by ocaisa** [comment]
Hi @Sabryr , I can do this. There's a PR from me, that details the updates I had to make for a new system: https://github.com/carpentries-incubator/hpc-intro/pull/312

I'll take about that and how we (want to) leverage HPC Carpentry within [CECAM](https://www.cecam.org/)

**Comment by Sabryr** [comment]
Supper, thank you Alan.
