### ISSUE TITLE
Missing scheduler name?

### ISSUE THREAD

**Issue by yesols** [carpentries-incubator/hpc-intro#369]
In the [_Working on a remote HPC system_](https://carpentries-incubator.github.io/hpc-intro/12-cluster/index.html) episode, it looks to me the actual name of the scheduler is missing in the following paragraph (under the heading _Nodes_)

> All interaction with the worker nodes is handled by a specialized piece of software called a scheduler (the scheduler used in this lesson is called ).

Did it mean to say, "the scheduler used in this lesson is called Slurm?"

**Comment by ocaisa** [comment]
Thanks for catching that, there was an error in the templating (I wonder if it is possible to catch these kinds of errors in ci)
