### ISSUE TITLE
Introductory presentation to establish vocabulary

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#375]
Based on feedback from a NIST teaching session, where learners complained about inconsistent use of terms like "node", "server", etc, which are used without definition or introduction in the lesson.

A candidate solution is to have the first unit be a presentation where broad concepts and vocabulary are introduced.

**Comment by reid-a** [comment]
Proposed outline:
- Introduce the laptop, as is currently done in the first part of lesson 11.
- Replace "when tasks take too long" with an introduction to different kinds of computers, their roles, and terminology.
  - Large single computers, conceptually like a laptop with a bigger CPU and more RAM.
  - Mainframes (?), big integrated multi-CPU machines with a single memory space
  - "The Cloud" -- arrays of disparately-sized computers doing different parts of a computational problem
  - Clusters and supercomputers, arrays of similar computer systems, differing by degree of integration, workload
- Introduce "server", "node", maybe "network", "machine", and be clear about their meaning within the lesson.
- Move on to more detailed examples, incorporating parts of the 2nd part.  
  - Audience participation to jolt learners back into the flow.

**Comment by reid-a** [comment]
Draft text now available [on the Codi](https://codimd.carpentries.org/AkjxTLCaSfeOWQ6zCkK8qA?both).

**Comment by tkphd** [comment]
Closed by #377
