### ISSUE TITLE
curl -o amdahl.tar.gz ... retrieves empty file

### ISSUE THREAD

**Issue by guyer** [carpentries-incubator/hpc-intro#455]
Tried on both macOS and linux cluster.

`wget -O amdahl.tar.gz https://github.com/hpc-carpentry/amdahl/tarball/main` works, as does clicking on https://github.com/hpc-carpentry/amdahl/tarball/main link in the browser.

**Comment by ocaisa** [comment]
Hmm, we are missing the `-L` option so that redirects are followed
