### ISSUE TITLE
"Scheduling jobs" -- remark about environment variables is incorrect

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#48]
In the "Scheduling jobs" episode, under the "other types of jobs" subsection, there is a remark that environment variables are not available for interactive jobs launched via "srun". On the two SLURM clusters available to me, this is not true for either of them -- doing "srun" followed by "env" shows that in the shell session, the "SLURM_*" environment variables are set, and the explicitly-mentioned SLURM_CPUS_PER_TASK variable is set if the "-c" flag was provided to "srun".

This might be configurable, and vary from one installation to another?

**Comment by psteinb** [comment]
Can you pinpoint me to the specific position in the episode, please?

**Comment by reid-a** [comment]
It's towards the end of the episode. In the "Other types of jobs" sub-heading, there's a paragraph that begins "srun takes the same options as sbatch" -- the parenthetical remark at the end of that paragraph is the wording I'm referring to.
