### ISSUE TITLE
"Accessing software", "Installing software of our own", more caution needed?

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#49]
In the "Accessing software" episode, in "Installing software of our own", it's not mentioned that some source distributions make bad assumptions about the level of privilege, and cluster users without root may need to provide "--prefix" info to the configuration step. They may also need to be prepared for odd or surprising output from the build.
It's possible that building software in a cluster environment should just be removed from "hpc-intro" (except perhaps to remark that it can be done), and put into an advanced follow-on lesson, if one is set up.

**Comment by psteinb** [comment]
My personal opinion on this is, that these considerations should go into [extras](https://github.com/hpc-carpentry/hpc-intro/tree/gh-pages/_extras) somewhere. This material should be an introduction to novices. Given the wide variety of backgrounds, I suggest to concentrate on concepts rather than details from the start. Thank you for pointing this out to me.

**Comment by baberlevi** [comment]
I'd like to see a whole section on installing software (I'm happy to help contribute to that). I think the 'accessing software' should basically end after the modules explanation with a 'You might need to install your own software someday, go read this other episode.'

**Comment by ChristinaLK** [comment]
@baberlevi that would be great!  I agree w/ @psteinb's previous comment that this would probably go into "extras" and not the workshop material proper, but if you'd like to give it a go, please do.

**Comment by bkmgit** [comment]
One could compile and or run a program with two different versions of a library and/or compiler. Introducing modules is helpful, but the current lesson is quite specific to a particular cluster. It should be made more generic.

**Comment by tkphd** [comment]
It's useful to have cluster-specific modules and commands, to make the lesson concrete. The site reads snippets for this part, so the repository is both generic (site builds against whatever snippet library you give it) and specific (site displays the snippet you've customized for your cluster).

The snippet architecture also resolved the original issue: if `--prefix` is required to work properly, the hosts can include that in their site-specific snippet library, and the learners will see exactly what their cluster requires on their screens / terminals.
