### ISSUE TITLE
UNIX terminology

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#55]
I think we should explain that Linux derived from the design of UNIX (but is not UNIX) and introduce the Linux & Posix  terms instead of UNIX throughout this unit.

**Comment by psteinb** [comment]
That is an interesting idea, but too high level for my taste given the learner profiles we are targeting here. the profiles are currently [being added](https://github.com/hpc-carpentry/hpc-carpentry.github.io/pull/15)

**Comment by bkmgit** [comment]
This may be better for Shell lesson and could be closed.

**Comment by psteinb** [comment]
Agreed. Please reopen at will or file a new issue in [hpc-shell](https://github.com/hpc-carpentry/hpc-shell) and friends.
