### ISSUE TITLE
filezilla for something with less adware 

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#57]
Filezilla has become riddled with adware and we (and others I assume) are steering users away from it.

I think we should suggest another tool on 15-transferring-files, WiinSCP, CyberDuck, etc.

**Comment by annajiat** [comment]
1. FileZilla has adware-free version as well in addition to bundled/sponsored installer.

2. Following Cyberduck download page shows almost pageful of ads and may trigger reCaptcha as well.
https://cyberduck.io/download/

For some reason, it was listed in 
https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Cyberduck.aspx

Users have reported getting malware,
https://trac.cyberduck.io/ticket/9738

Cyberduck being downloaded from many different websites results in malware as well
https://blog.cyberduck.io/2015/11/17/mind-the-adware/


3. WinSCP had complaints too. It is windows only.
https://en.wikipedia.org/wiki/WinSCP#Advertisements_in_installer

3rd party mac port seems to be abandoned 
https://portingteam.com/index.php/files/file/7089-winscp/

WinSCP download page seems to be cluttered with more ads
https://winscp.net/eng/downloads.php


Overall:
Users searching for these three by themselves might get malware/adware bundled version from many download websites on the Internet.

FileZilla website did not seem to have external ads other than of its own pro version. 
On the other hand, CyberDuck and WinSCP sites and download pages seem to have lots of ads which may potentially show irrelevant software/download links leading to malware or at least be confusing to the users.

https://www.forbes.com/sites/leemathews/2018/01/26/hackers-abuse-google-ad-network-to-spread-malware-that-mines-cryptocurrency/#2b7d24578662

https://cyware.com/news/new-malvertising-variant-leverages-google-ads-to-serve-malware-through-legitimate-websites-e0936a88


Recommendations:
All of these three are pretty useful. If a change is necessary, we might choose to provide a short list of the alternatives: FileZilla, CyberDuck, and then WinSCP (in order) along with the recommended download URL and with a note that it may not be safe to download it from links/sites other than the given recommended download links. The reason for ordering is first two being cross-platform.

We can choose to directly link to following page for adware free installer of FileZilla, 
https://filezilla-project.org/download.php?show_all=1

followed by,

CyberDuck: https://cyberduck.io/download/

WinSCP: https://winscp.net/eng/downloads.php

**Comment by tkphd** [comment]
Git for Windows ships with `scp`, and macOS and Linux have it by default. We could avoid any adware by stripping out the GUI file transfer section entirely.

**Comment by colinsauze** [comment]
Windows ships with scp and sftp now as well.

**Comment by Sabryr** [comment]
+1 for scp

**Comment by bkmgit** [comment]
Current lesson primarily uses scp. See https://carpentries-incubator.github.io/hpc-intro/15-transferring-files/index.html . Filezilla is mentioned as some audiences may prefer a graphical user interface. Filezilla is cross platform, so is suitable for a broad audience. Current link to https://filezilla-project.org/ works, so issue can be closed.
