### ISSUE TITLE
data locality

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#58]
On 15-transferring-files: Add an explanation of data locality, and how to not do things like use scp on your macbook in your office (or worse yet at home on vpn) to scp files from the file storage at a facility to the HPC storage.  Something like: https://researchit.las.iastate.edu/move-your-files-faster but more generic.

**Comment by bkmgit** [comment]
Pull request #245  put in for this. If ok, this can be closed.

**Comment by reid-a** [comment]
PR #245 has been merged, closing this.
