### ISSUE TITLE
Loading a module by default

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#61]
14-modules talks about putting 'module load' commands in .bachrc and .bash_profile.

1. I generally discourage users from doing this. It often slows down their login session, they forget they have them and then later open tickets about things behaving oddly, module names can change, etc. 

2. If it's to be kept, we should at least explain the difference between the two conf files, and issue a word of caution about why it may cause problems

**Comment by ChristinaLK** [comment]
I agree with this -- in general, I think it's good for researchers to always be aware/conscious of these things instead of making them automatic and then forgetting about them.

**Comment by psteinb** [comment]
I fully agree with both of you. Please submit a PR.

**Comment by Sabryr** [comment]
I stumbled on this once again. Would very much like to send a PR but there are some major revision PRs pending
