### ISSUE TITLE
address internet connectivity issues common to clusters

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#62]
15-transferring-files talks about using wget to grab files from the internets.  We should also include a warning about some clusters not being able to get to the internet at all, or maybe only a head node or DTN node being setup for internet access.

**Comment by psteinb** [comment]
True, please submit a PR. I guess a `callout` section would be most suitable for something like this.

**Comment by ChristinaLK** [comment]
agree with @psteinb
