### ISSUE TITLE
longer introduction to ssh

### ISSUE THREAD

**Issue by Carreau** [carpentries-incubator/hpc-intro#69]
Hi, 

I'm going through the lesson material, and the step from `11-hpc-intro.md` to `12-cluster.md` feels a bit rough. 

    Go ahead and log in to the cluster.
    ```
    [user@laptop]$ ssh remote
    ```
    {: .bash}

    Very often, many users are tempted to think of a high-performance computing installation as one
    giant, magical machine. Sometimes, people will assume that the computer they've logged onto is the
    entire computing cluster. So what's really happening? What computer have we logged on to? The name
    of the current computer we are logged onto can be checked with the `hostname` command. (Clever users
    will notice that the current hostname is also part of our prompt!)

    ```
    [remote]$ hostname
    ```

Now we can assume that user now about shell, and guess that `ssh` is a command and `remote` is an argument. But from experience assuming that they understand the `[remote]$` prompt is a prompt of the remote machine if a big leap of faith. 

I see a number of step missing here that IMHO need to be explained.: 
  - ssh allow you to connect to a remote machine  – as if you plugged a screen/keyboard/(mouse?) to a remote computer and open a terminal. 
  - the `remote` argument is not actually the word remote, but the actual remote address of the cluster (given to you by your admin). You also (likely) want to prefix it by `<username>@`
  - You will (likely) need to type your password and _it won't show up_ on the screen while you type.
  - if the password is correct your terminal should now see a welcome message from the cluster, and everything you run in this terminal is now executed on a remote machine.
(details may varies between installations)

I believe that would be the basic of what need to be covered, but I feel like understanding local machine vs remote machine and when we are where is critical. Alternatively this could be in a separate lessons, but I don't see it in the shell-novices.

**Comment by psteinb** [comment]
excellent points, @Carreau . thank you for opening an issue. We currently know that this material has quite some rough edges. When time permits, I am currently trying to rewrite it with the feedback of the community (help is welcome on this!). I am basing these changes on my [own open-source material](https://psteinb.github.io/hpc-in-a-day/) ... which I just checked and they also don't touch on the issues you mentioned. Feel free to send a PR. I'll follow up on your comments in #65 when time allows.

**Comment by reid-a** [comment]
I wonder how much of this can be covered in set-up? After all, users will not be successful in connecting to the cluster if they do not have accounts there, so possibly an explanation of the SSH infrastructure could accompany the account-generation process. I certainly agree that the local vs remote distinction needs emphasis within the lesson itself. 

I am slightly hesitant, because on the one hand, I know from experience that set-up activities are sometimes rushed through or skipped entirely, but on the other hand, time spent here is time that is not available for the HPC material that is unique to this lesson.

**Comment by psteinb** [comment]
I'd object to move this into setup. In my workshops, a subjective 50% of 
the participants have trouble grasping the notion that the cluster is 
something remote and that you have to connect to it. This is why I 
recommend leaving it there.

**Comment by reid-a** [comment]
To be clear, what I was thinking should be in set-up is not the remote character of the shell, but merely the SSH logistics -- @Carreau suggested the lesson should clarify e.g. that the "ssh" shell command allows you to connect to a remote machine, that you might have to provide your password to complete the connection, which feels like set-up info to me.

But, it's of course correct for your experience to override my intuition -- certainly the fact of having a shell on a remote machine is new, and deserves emphasis, and maybe the ssh logistics can't be separated from it, or are brief enough that it's worth re-iterating.

**Comment by Carreau** [comment]
I think that's one of the place where we do not have a one-size fits all. 

I've definitely given cluster-101 where all the attendees had cluster accounts, and other where they do not. On our cluster we have on purpose ~60 guestXXX account for such purpose. 

I guess it might be complicated, but would it make sens to replace some of the ssh commands (hostname..etc) with variables, so that at least connect instructions could be customised on a per site basis ? 

For the logistic part of giving access and setting up, I think it makes a lot of sens to ask workshop organisers to do setup accounts for most of the users. But I don't believe you can really rely on that and should get some fallback.

When this is a two days workshop, and when this is given in second day, you _could_ start one of the first day lesson by making sure people have account and know their credentials, that give them ~24 hours to get ready. 

Another thing I did not mentioned, but which I believe is critical to flawless interaction is setting up ssh-keys.
