### ISSUE TITLE
"Customising a job" section, pay attention to copy past. 

### ISSUE THREAD

**Issue by Carreau** [carpentries-incubator/hpc-intro#70]
One regular issue we have in HPC at UC Merced is with copy past. 
Some OS/text editor/etc try to be "helpful" and convert `--`/`-` to em dashes, and [`u0096`](http://www.fileformat.info/info/unicode/char/96/index.htm) it can be relatively hard to diagnose, in the cli you can use `grep $'u0096'` (on bash 4.2+ I believe) to find those. 

It is relatively sneaky as there is no errors, and flags get just ignore on sbatch. 
This is rare but recurrent for user who create batch script on their machine in word/text-edit and then upload to the cluster. 

Might not be a good thing in the lesson itself, but for the instructors notes.

**Comment by ChristinaLK** [comment]
agreed!

**Comment by tkphd** [comment]
I've done a scan of the repository, and at this time, can find no instances of the [en dash](http://www.unicode-symbol.com/u/2013.html), [em dash](http://www.unicode-symbol.com/u/2014.html), [start of guarded area](http://www.unicode-symbol.com/u/0096.html), or [horizontal bar](http://www.unicode-symbol.com/u/2014.html) symbols.

```bash
$ for symbol in {"\u0096","\u2013","\u2014","\u2015"}; do
>     find . -type f -exec grep -l ${symbol} {} \;
> done
```
```bash
$ for symbol in {–,—,―}; do
>     find . -type f -exec grep -l ${symbol} {} \;
> done
./.git/objects/pack/pack-c64d26afdb1fb526581998c322518119facaeaf6.pack
./.git/objects/pack/pack-c64d26afdb1fb526581998c322518119facaeaf6.pack
./.git/objects/pack/pack-d9980979495136c76afce5479fb4d56f43909e79.pack
./files/bash-lesson.tar.gz
./.git/objects/pack/pack-c64d26afdb1fb526581998c322518119facaeaf6.pack
```

To my knowledge, we're not propagating such errors. We can introduce a blurb in the Instructor Notes to warn people off the sin of copy-paste from Stackoverflow, etc., but this is (as you noted) not a core issue for our curriculum.

**Comment by bkmgit** [comment]
May be better in instructor notes. Possibly also relevant for shell lesson.
