### ISSUE TITLE
Mistake in sbatch options ?

### ISSUE THREAD

**Issue by Carreau** [carpentries-incubator/hpc-intro#72]
```
Resource requests
But what [.....], which is probably not what we want.

The following are several key resource requests:

-n <nnodes> - how many nodes does your job need?

-c <ncpus> - How many CPUs does your job need?
```

- I believe `-n` is the number of tasks, the number of nodes is uppercase `-N`, 
- `-c` is the number of CPU but per task, written as above, it feels like it's the total number of CPU.

**Comment by psteinb** [comment]
Indeed this is a mistake. Feel free to send a PR.

**Comment by tkphd** [comment]
This has been addressed in the snippet libraries.
