### ISSUE TITLE
Improvements to Episode 2 (Working on a cluster)

### ISSUE THREAD

**Issue by Sabryr** [carpentries-incubator/hpc-intro#79]
Notes for possible PRs (I haven't gone through all the material yet, so some of the following may be addressed later).
1. Why shouldn't we run long jobs on login nodes. 
2. A diagram to show the login process from laptop to login node via internet and how the login nodes are used to interact with the worker nodes.
3. Elaborate more on, availability of common storage, place in one location and access  from any worker node (much faster than through internet). A diagram to show all compute nodes are connected to each other and to the common storage.
4. Photos or CPU and memory and disk (to show these are not mystical stuff but physical objects)
5. When showing nproc,  sinfo and free -n, show "df -h" to see available storage locations.

**Comment by psteinb** [comment]
Hi Sabyr,
thanks for opening this issue. I fully support 1 & 2. On 3. you mean to discuss the shared file system, right? On 4. I've had mixed success with similar approaches, but still think that its a good idea. On 5. this part needs to be reworked as it currently is too SLURM and site specific. Further, there is quite a large possibility to talk about concepts that have not been touched.

**Comment by psteinb** [comment]
It's still the plan to implement the configuration trick you mentioned in this repo. Feel free to open an PR if you want. I already adopted [lesson-outline.md](https://github.com/hpc-carpentry/hpc-intro/blob/gh-pages/lesson-outline.md) in this direction, which might work as a guideline. However, at the last video call, people expressed strong interest to reiterate on this lesson-outline. So I am waiting for any more contributions until that discussion has come to a conclusion. @ChristinaLK @devbioinfoguy

**Comment by ChristinaLK** [comment]
We should probably nail down who is adding the configuration trick.  I thought @aturner-epcc might be doing it, but at this point, I think anyone who adds it would be a hero. :)

**Comment by devbioinfoguy** [comment]
Agreed. I think everyone is looking forward to this.

-B

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

Bob Freeman, PhD
Director, Research Technology Operations @ Research Computing Services
Division of Research and Faculty Development    HARVARD | BUSINESS | SCHOOL
Baker Library & Bloomberg Center B96    25 Harvard Way, Boston, MA 02163

617.496.6612, phone    @DevBizInfoGuy    http://bit.ly/whatAboutBob2

For more information –
RCS:                http://intranet.hbs.edu/dept/research/
Software:          http://intranet.hbs.edu/dept/research/software/
Rsrch Grid:        http://grid.rcs.hbs.org<http://grid.rcs.hbs.org/>
Training:            http://training.rcs.hbs.org<http://training.rcs.hbs.org/>

**Comment by aturner-epcc** [comment]
It is in progress at my end - hope to have it in the next couple of weeks. Worst case by the end of Feb. I'll assign this to me.

**Comment by psteinb** [comment]
You mean [this](https://github.com/hpc-carpentry/hpc-intro/pull/73/files?utf8=%E2%9C%93&diff=unified#diff-aeb42283af8ef8e9da40ededd3ae2ab2R77) in PR #73 ?

**Comment by Sabryr** [comment]
@aturner-epcc , I could help with this if you need. Is it possible to submit a issue specific for this (which issue did you assign it to yourself ? ) and a WIP PR.  (sorry for pushing I would very much like to use this material in a workshop)

**Comment by aturner-epcc** [comment]
I have stopped doing anything until #73 is merged and we make a plan for how to take this forwards. I do not want to tread on @psteinb and others toes and was only doing stuff to be useful, not to take over this, it was all Peter's ideas and he should get the credit.

I have a working version with auto-includes for PBS Pro on our system that required a few more customisation variables than in Peter's original implementation. Should we open a new issue specifically to discuss auto-includes so we can capture everything in one place going forward? I feel like we have struggled as discussion is spread across multiple threads....

**Comment by psteinb** [comment]
@aturner-epcc thanks for stepping in. I totally agree. And yes, please open an issue on auto-includes. I am curious on what you found.

**Comment by aturner-epcc** [comment]
Autoconfig now in via #101 . Need to reassess the original issues raised and split out into separate issues that we can work to address.

**Comment by tkphd** [comment]
Items 2 and 4 have been resolved by @Sabryr's contribution of original artwork.

**Comment by tkphd** [comment]
Item 5 was resolved separately (`df -Th` alongside `nproc` and `sinfo` exercises).

**Comment by tkphd** [comment]
Broke out item 3 as #251. This combined issue is deprecated, in favor of discussing the specific topics separately.
