### ISSUE TITLE
Consolidating "file transfer" into one section

### ISSUE THREAD

**Issue by wirawan0** [carpentries-incubator/hpc-intro#86]
I want to add an input toward the simplification of "file transfer" topic. There are currently two places where this was touched:

* "Transferring Data" under "Working on a cluster" episode: https://hpc-carpentry.github.io/hpc-intro/12-cluster/index.html#transferring-data

* "Transferring Files", a dedicated episode:
https://hpc-carpentry.github.io/hpc-intro/15-transferring-files/index.html

I wonder if we can consider consolidating all into one episode. Perhaps on top subheadings there will be the "preferred" method. Then on the latter subheadings, we present several alternatives. Instructors can pick and choose what method they want to expose the learners to.

A second alternative is to push the alternative methods to an extra episode, per @psteinb suggestion in #27.

PS: I'm aware of issue 27, [Simplify file transfer section](https://github.com/hpc-carpentry/hpc-intro/issues/27), but that one was on suggestion to focus only on one method of file transfer. 

What is everyone's thought on this? I won't mind helping doing the consolidation/reorg, but I want to get your input first.

**Comment by ChristinaLK** [comment]
I think we were going to move some of this to an "extra" page? Can't remember now.

**Comment by ruillercoaster** [comment]
It is kind of confusing to have wget/sftp and scp in the same section for me. Especially, when I review the content and look for references after the workshop. My personal opinion is that the scp in the introduction part is already very thoroughly explained. I can easily search futher from there. However, putting the section to a proper chapter other than introduction is appreciated.

**Comment by tkphd** [comment]
The cluster episode no longer contains a data transfer section.
